<?xml version="1.0"?>
<package format="3">
  <name>aws_robomaker_hospital_world</name>
  <version>1.0.0</version>
  <description>
    AWS RoboMaker package for a hospital world with multiple rooms and furniture for Gazebo simulations.
  </description>
  <license>Apache-2.0</license>
  <author email="ros-contributions@amazon.com">AWS RoboMaker</author>
  <maintainer email="ros-contributions@amazon.com">AWS RoboMaker</maintainer>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>gazebo_ros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
    <gazebo_ros gazebo_model_path="${prefix}/share/aws_robomaker_hospital_world/models:${prefix}/share/aws_robomaker_hospital_world/fuel_models"/>
  </export>
</package>
